modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "rssearchfix"
version = "1.0.0"
displayName = "RS Search Fix"
description = '''
Refined Storage Search Fix:
- # → Tag Search, $ → Tooltip Search
- Search by item id
'''

[[dependencies.rssearchfix]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rssearchfix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rssearchfix]]
    modId = "refinedstorage"
    mandatory = true
    versionRange = "[1.12,)"
    ordering = "AFTER"
    side = "CLIENT"
